---
- name: Check for supported version
  fail:
    msg: "Please use a supported OS, detected: {{ ansible_distribution }}"
  when: ansible_distribution != "RedHat"
- include: access_control.yml
- include: audit_and_accountability.yml
- include: configuration_management.yml
- include: identification_and_authentication.yml
- include: incident_response.yml
- include: maintenance.yml
- include: misc.yml
- include: gnome.yml
- include: system_and_communications_protection.yml
- include: system_and_information_integregity.yml
- include: system_and_services_acquisition.yml
- include: media_protection.yml
- include: scap.yml
