---
- name: Check for supported version
  fail:
    msg: "Please use a supported OS, detected: {{ ansible_distribution }}"
  when: ansible_distribution != "RedHat"

- include: system_settings/main.yml
- include: services/main.yml


- include: finalize.yml
- include: scap.yml
