- name: Ensure libselinux-python bindings are installed
  yum:
    name: libselinux-python
    state: present
    disablerepo: "*"
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms

- name: Check for pub key files
  find:
    paths: /
    patterns: "^.*?(?:.pub)$"
    recurse: yes
    use_regex: True
  register: result

- name: AC-6(2) Restrict Virtual Console Root Logins
  lineinfile:
    dest: /etc/securetty
    regexp: '^vc'
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-6(2) Restrict Serial Port Root Logins
  lineinfile:
    dest: /etc/securetty
    regexp: 'ttyS[0-9]'
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: List Users
  shell: "cat /etc/passwd | cut -d: -f1"
  register: system_users
  changed_when: False

- name: List UIDs
  shell: "cat /etc/passwd | cut -d: -f3"
  register: system_uids
  changed_when: False

- name: AC-6(8) Ensure that System Accounts Do Not Run a Shell Upon Login
  with_together:
    - "{{ system_users.stdout_lines }}"
    - "{{ system_uids.stdout_lines }}"
  user:
    name: "{{ item.0 }}"
    shell: /sbin/nologin
  when: (item.1 < 500) and (item.1 > 0)
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-6 Verify Only Root Has UID 0
  with_together:
    - "{{ system_users.stdout_lines }}"
    - "{{ system_uids.stdout_lines }}"
  user:
    name: "{{ item.0 }}"
    state: absent
  when: (item.1 == 0) and (item.0 != "root")
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-2 Set Password Minimum Digit Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: '^dcredit ='
    line: "dcredit = -1"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-2 Set Password Minimum Uppercase Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: '^ucredit ='
    line: "ucredit = -1"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-2 Set Password Minimum Special Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: 'ocredit ='
    line: "ocredit = -1"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-2 Set Password Minimum Lowercase Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: '^lcredit ='
    line: "lcredit = -1"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-2 Set Password Strength Minimum Different Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: '^difok ='
    line: "difok = 4"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-6 Check ownership and permissions on /etc/shadow
  file:
    path: /etc/shadow
    owner: root
    group: root
    mode: 0000
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-6 Check ownership and permissions on /etc/group
  file:
    path: /etc/group
    owner: root
    group: root
    mode: 0644
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-6 Check ownership and permissions on /etc/passwd
  file:
    path: /etc/passwd
    owner: root
    group: root
    mode: 0644
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-6 Check ownership and permissions on /etc/group
  file:
    path: /etc/passwd
    owner: root
    group: root
    mode: 0644
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-6 Verify that Shared Library Files Have Restrictive Permissions
  with_items: "{{ shared_lib_path }}"
  file: path="{{ item }}" state=directory follow=yes recurse=yes mode="go-w"
  ignore_errors: true

- name: AC-6 Verify that Shared Library Files Have Restrictive Permissions
  with_items: "{{ shared_lib_path }}"
  file: path="{{ item }}" state=directory follow=yes recurse=yes owner=root group=root
  ignore_errors: true

- name: AC-6 Verify that System Executables Have Restrictive Permissions
  with_items: "{{ executables_path }}"
  file: path="{{ item }}" state=directory follow=yes recurse=yes mode="go-w"
  ignore_errors: true

- name: AC-6 Verify that System Executables Have Root Ownership
  with_items: "{{ executables_path }}"
  file: path="{{ item }}" state=directory follow=yes recurse=yes owner=root group=root
  ignore_errors: true

- name: AC-6 System Audit Logs Must Have Mode 0640 or Less Permissive
  file:
    path: /var/log/audit/audit.log
    mode: 640
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-8(a),AC-8(b),AC-(c) Enable SSH Warning Banner
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'Banner /etc/issue'
    line: 'Banner /etc/issue'
  notify:
    - reload ssh
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-8(a),AC-8(b),AC-(c) Modify the System Login Banner - /etc/issue
  copy:
    src: issue
    dest: /etc/issue
    group: root
    owner: root
    mode: 644
    force: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-8(a),AC-8(b),AC-(c) Modify the System Login Banner - /etc/issue.net
  copy:
    src: issue
    dest: /etc/issue.net
    group: root
    owner: root
    mode: 644
    force: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-8(a),AC-8(b),AC-(c) Modify the System Login Banner - /etc/motd
  copy:
    src: issue
    dest: /etc/motd
    group: root
    owner: root
    mode: 644
    force: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high


- name: AC-4 Disable Kernel Parameter for Sending ICMP Redirects by Default
  sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: AC-4 Disable Kernel Parameter for Accepting Secure Redirects for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: AC-17(7) Enable Kernel Parameter to Log Martian Packets
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: AC-4 Disable Kernel Parameter for Accepting Source-Routed Packets By Default
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: AC-4 Disable Kernel Parameter for Accepting Secure Redirects By Default
  sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: AC-4 Disable Kernel Parameter for Accepting ICMP Redirects By Default
  sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: AC-4 Enable Kernel Parameter to Use TCP Syncookies
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: AC-4 Enable Kernel Parameter to Use Reverse Path Filtering for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: AC-4 Enable Kernel Parameter to Use Reverse Path Filtering by Default
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: AC-19(a),AC-19(d),AC-19(e),AC-17(8)  Stop and disable services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
#  failed_when: "stop_disabled_services | failed and 'no service or tool found for: {{ item }}' not in stop_disabled_services.msg"
  ignore_errors: true
  register: stop_disabled_services
  with_items: "{{ ac_disable_services }}"
  when: ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-19(a),AC-19(d),AC-19(e),AC-17(8)  Stop and disable services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
#  failed_when: "stop_disabled_services | failed and 'systemd could not find the requested service' not in stop_disabled_services.msg"
  ignore_errors: true
  register: stop_disabled_services
  with_items: "{{ ac_disable_services }}"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-17(8) Uninstall Unnecessary Package
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ ac_uninstall_packages }}"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-3,AC-3(3),AC-4,AC-6 Enable SELinux
  selinux:
    policy: targeted
    state: enforcing
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: Set SELinux to Enforcing
  command: /usr/sbin/setenforce 1
  when: ansible_selinux.mode == 'permissive'

- name: AC-17(8) Remove Rsh Trust Files - /etc/hosts.equiv
  file:
    dest: /etc/hosts.equiv
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: Find User Rsh Trust Files
  shell: "find /home -name '.rhosts' -print"
  register: user_rhosts
  check_mode: no
  changed_when: False

- name: AC-17(8) Remove Rsh Trust Files - ~/.rhosts
  with_items: "{{ user_rhosts.stdout_lines }}"
  file:
    dest: "{{ item }}"
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high


- name: AC-3,AC-3(3),AC-6 Ensure SELinux Not Disabled in /etc/grub.conf
  replace:
    dest: /etc/grub.conf
    regexp: "selinux=0"
  when: ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-3,AC-3(3),AC-6 Ensure SELinux Not Disabled in /etc/grub2.conf
  replace:
    dest: /etc/grub2.cfg
    regexp: "selinux=0"
  notify: apply grub2 changes
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-19(a), AC-19(d), AC-19(e) Disable Modprobe Loading of USB Storage Driver - Ensure usb-storage.conf is present
  copy:
    src: usb-storage.conf
    dest: /etc/modprobe.d/usb-storage.conf

- name: AC-6 Set Daemon Umask
  replace:
    dest: /etc/init.d/functions
    regexp: 'umask.*'
    replace: 'umask 027'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high

- name: AC-2(2),AC-2(3) Set Account Expiration Following Inactivity
  lineinfile:
    dest: /etc/default/useradd
    regexp: '.*INACTIVE.*'
    line: 'INACTIVE=35'

- name: AC-10 Limit the Number of Concurrent Login Sessions Allowed Per User
  lineinfile:
    dest: /etc/security/limits.conf
    regexp: '.* hard maxlogins .*'
    line: "* hard maxlogins 10"

- name: AC-3 Disable Interactive Boot
  lineinfile:
    dest: /etc/sysconfig/init
    regexp: '.*PROMPT.*'
    line: 'PROMPT=no'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-18(a),AC-18(d),AC-18(3) Disable Bluetooth Kernel Modules
  copy:
    src: bluetooth.conf
    dest: /etc/modprobe.d/bluetooth.conf

- name: AC-18(a),AC-18(d),AC-18(3) Disable Bluetooth Service
  service:
    name: bluetooth
    enabled: no
    state: stopped
  ignore_errors: yes

- name: AC-17 Install openswan or libreswan Package
  yum:
    name: "{{ vpn_package }}"
    state: present
    disablerepo: '*'
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms

- name: AC-2(5),RHEL-07-040190 Set SSH Idle Timeout Interval
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ".*ClientAliveInterval.*"
    line: "ClientAliveInterval 600"
  tags:
    - CAT-II

- name: AC-2(5, RHEL-07-040191 Set SSH Idle Timeout Interval
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ".*ClientAliveCountMax.*"
    line: "ClientAliveCountMax 0"
  tags:
    - CAT-II

- name: AC-3, AC-17(2) Use Only Approved Ciphers
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ".*Ciphers.*"
    line: "Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc"

- name: Ensure audit is Installed
  yum:
    name: audit
    state: present
    disablerepo: '*'
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms

- name: Enable auditd service
  service:
    name: auditd
    state: started
    enabled: yes

- name: Get Underlying Architecture for Audit Rules
  shell: getconf LONG_BIT
  register: audit_arch

- name: AC-3(10) Add Audit Rules - b32
  copy:
    src: audit-800-53-b32.rules
    dest: /etc/audit/rules.d/audit-800-53-b32.rules
    force: yes
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-3(10) Add Audit Rules - b64
  copy:
    src: audit-800-53-b64.rules
    dest: /etc/audit/rules.d/audit-800-53-b64.rules
    force: yes
  notify: reload auditd
  when: audit_arch.stdout == '64'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-3(10) Add Audit Rules - common
  copy:
    src: audit-800-53-common.rules
    dest: /etc/audit/rules.d/audit-800-53-common.rules
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: Find commands with setuid/setgid bit set on /
  shell: find / -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null
  check_mode: no
  register: find_result

- name: AC-3(10)) Ensure auditd Collects Information on the Use of Privileged Commands
  template:
    src: privileged-commands.rules.j2
    dest: /etc/audit/rules.d/privileged-commands.rules
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-9 System Audit Logs Must Have Mode 0640 or Less Permissive (1/4)
  file:
    path: /var/log/audit/audit.log
    mode: 0640
    state: file
    group: root
    owner: root
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AC-17(1) Enable Auditing for Processes Which Start Prior to the Audit Daemon
  shell: /sbin/grubby --update-kernel=ALL --args="audit=1"

- name: AC-7(a) Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/system-auth (1/3)
  lineinfile:
    dest: /etc/pam.d/system-auth
    insertbefore: "^auth.*pam_unix.so.*"
    line: "auth         required      pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900"

- name: AC-7(a) Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/system-auth (2/3)
  lineinfile:
    dest: /etc/pam.d/system-auth
    insertafter: "^auth.*pam_unix.so.*"
    line: "auth      [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900"

- name: AC-7(a) Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/system-auth (3/3)
  lineinfile:
    dest: /etc/pam.d/system-auth
    insertbefore: "^account.*pam_unix.so.*"
    line: "account     required      pam_faillock.so"

- name: AC-7(a) Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/password-auth (1/3)
  lineinfile:
    dest: /etc/pam.d/password-auth
    insertbefore: "^auth.*pam_unix.so.*"
    line: "auth         required    pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900"

- name: AC-7(a) Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/password-auth (2/3)
  lineinfile:
    dest: /etc/pam.d/password-auth
    insertafter: "^auth.*pam_unix.so.*"
    line: "auth      [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900"

- name: AC-7(a) Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/password-auth (3/3)
  lineinfile:
    dest: /etc/pam.d/password-auth
    insertbefore: "^account.*pam_unix.so.*"
    line: "account       required      pam_faillock.so"

- name: AC-17(2),68,2450
  yum: name="{{ item }}" state=latest
  with_items: "{{ ac_install_packages }}"

- name: AC-3, 213 Set the UEFI Boot Loader Password RHEL-07-010470
  stat: path=/sys/firmware/efi
  register: efi

- name: Checking if efi exists
  stat: path=/boot/efi
  register: efi

- name: AC-3, 213 Set the UEFI Boot Loader Password RHEL-07-010470
  shell: grep "password_pbkdf2" /etc/efi/EFI/redhat/grub.cfg
  when:
  - efi.stat.exists == true
  - ansible_distribution_major_version == "7"

- debug: msg="EFI does not exist"
  when: efi.stat.exists == false

- name: AC-3,CM-6(b),366,RHEL-07-010442 Disable Host-Based Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "HostbasedAuthentication no"
    state: present
  tags:
    - CAT-II

- name: AC-6,RHEL-06-000518 Verify and Correct File Permissions with RPM
  shell: for FILE_PATH in $(rpm -Va | grep '^.M'); do rpm --setperms $(rpm -qf "$FILE_PATH"); done
