- name: AU-9 Enable SELinux
  selinux:
    policy: targeted
    state: enforcing
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AU-9 Ensure SELinux Not Disabled in /etc/grub.conf
  replace:
    dest: /etc/grub.conf
    regexp: "selinux=0"
  when: ansible_distribution_major_version == 6
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AU-9 Ensure SELinux Not Disabled in /etc/grub2.conf
  replace:
    dest: /etc/grub2.cfg
    regexp: "selinux=0"
  notify: apply grub2 changes
  when: ansible_distribution_major_version == 7
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: Ensure audit is Installed
  yum:
    name: audit
    state: present
    disablerepo: '*'
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms

- name: Enable auditd service
  service:
    name: auditd
    state: started
    enabled: yes

- name: AU-6,AU-1(b),AU-9 System Audit Logs Must Have Mode 0640 or Less Permissive
  file:
    path: /var/log/audit/audit.log
    mode: 640
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name:  AU-14(1),AU-1(b),AU-2(a),AU-2(c),AU-2(d),AU-10 Enable Auditing for Processes Which Start Prior to the Audit Daemon
  shell: /sbin/grubby --update-kernel=ALL --args="audit=1"

- name: Get Underlying Architecture for Audit Rules
  shell: getconf LONG_BIT
  register: audit_arch

- name: AU-1(b), AU-2(a), AU-2(c), AU-2(d), AU-12(a), AU-12(c) Add Audit Rules - b32
  copy:
    src: audit-800-53-b32.rules
    dest: /etc/audit/rules.d/audit-800-53-b32.rules
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AU-1(b), AU-2(a), AU-2(c), AU-2(d), AU-12(a), AU-12(c) Add Audit Rules - b64
  copy:
    src: audit-800-53-b32.rules
    dest: /etc/audit/rules.d/audit-800-53-b64.rules
  notify: reload auditd
  when: audit_arch.stdout == '64'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AU-1(b), AU-2(a), AU-2(c), AU-2(d), AU-12(a), AU-12(c) Add Audit Rules - common
  copy:
    src: audit-800-53-common.rules
    dest: /etc/audit/rules.d/audit-800-53-common.rules
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: Find commands with setuid/setgid bit set on /
  shell: find / -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null
  check_mode: no
  register: find_result

- name:  AU-1(b), AU-2(a), AU-2(c), AU-2(d), AC-6(9), AU-12(a), AU-12(c) Ensure auditd Collects Information on the Use of Privileged Commands
  template:
    src: privileged-commands.rules.j2
    dest: /etc/audit/rules.d/privileged-commands.rules
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AU-1(b), AU-9 System Audit Logs Must Have Mode 0640 or Less Permissive (1/4)
  file:
    path: /var/log/audit/audit.log
    mode: 0640
    state: file
    group: root
    owner: root
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
- name: AU-1(b), AU-4, AU-5(b) Configure auditd space_left Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "space_left_action = email"
    regexp: "^space_left_action*"
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: AU-1(b), AU-4, AU-5(b) Configure auditd admin_space_left Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "admin_space_left_action = single"
    regexp: "^admin_space_left_action*"
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: AU-1(b),AU-4,AU-5(1),AU-5(a),IR-5,RHEL-07-030352 Configure auditd mail_acct Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "action_mail_acct = root"
    state: present
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
