- name: CM-2(1)(b),366,RHEL-07-040540 Enable X11 Forwarding
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'X11Forwarding yes'
    state: present
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-I

- name: CM-7 Disable Kernel Parameter for Sending ICMP Redirects by Default
  sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: CM-7 Disable Kernel Parameter for Sending ICMP Redirects for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: CM-7 Disable Kernel Parameter for Accepting Secure Redirects for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: CM-7,RHEL-07-040730 Disable Kernel Parameter for IP Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: CM-7,RHEL-07-040350 Disable Kernel Parameter for Accepting Source-Routed Packets for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: CM-7 Disable Kernel Parameter for Accepting ICMP Redirects for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Disable Kernel Parameter for Accepting Secure Redirects for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Enable Kernel Parameter to Log Martian Packets
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7,RHEL-07-040351 Disable Kernel Parameter for Accepting Source-Routed Packets By Default
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: CM-7 Disable Kernel Parameter for Accepting Secure Redirects By Default
  sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Disable Kernel Parameter for Accepting ICMP Redirects By Default
  sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7,RHEL-07-040380 Enable Kernel Parameter to Ignore ICMP Broadcast Echo Requests
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: CM-7 Enable Kernel Parameter to Ignore Bogus ICMP Error Responses
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Disable IPv6 Networking Support Automatic Loading
  lineinfile:
    dest: /etc/modprobe.d/disabled.conf
    create: yes
    regexp: '^options ipv6 disable.*'
    line: 'options ipv6 disable=1'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Disable Accepting IPv6 Redirects
  sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Disable DCCP Support
  lineinfile:
    dest: /etc/modprobe.d/system.conf
    create: yes
    regexp: 'install dccp'
    line: 'install dccp /bin/false'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Disable SCTP Support
  lineinfile:
    dest: /etc/modprobe.d/system.conf
    create: yes
    regexp: 'install sctp'
    line: 'install sctp /bin/false'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Disable RDS Support
  lineinfile:
    dest: /etc/modprobe.d/system.conf
    create: yes
    regexp: 'install rds'
    line: 'install rds /bin/false'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Disable TIPC Support
  lineinfile:
    dest: /etc/modprobe.d/system.conf
    create: yes
    regexp: 'install tipc'
    line: 'install tipc /bin/false'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7,CM-6(b),366,4.7,RHEL-07-040290 Install CM Packages
  yum:
    name: "{{ item }}"
    state: present
    disablerepo: '*'
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms
  with_items: "{{ cm_install_packages }}"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: CM-7 Enable CM services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ cm_enable_services }}"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Install NTP Service
  yum:
    name: ntp
    state: present
    disablerepo: '*'
    enablerepo: rhel-6-server-rpms
  when: ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Enable NTP Service (ntpd)
  service:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Stop and disable services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  failed_when: "stop_disabled_services | failed and 'no service or tool found for: {{ item }}' not in stop_disabled_services.msg"
  register: stop_disabled_services
  with_items: "{{ cm_disable_services }}"
  when: ansible_distribution_major_version == "6"
  ignore_errors: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Stop and disable services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  failed_when: "stop_disabled_services | failed and 'systemd could not find the requested service' not in stop_disabled_services.msg"
  register: stop_disabled_services
  with_items: "{{ cm_disable_services }}"
  when: ansible_distribution_major_version == "7"
  ignore_errors: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7  Stop and disable rhnsd
  service:
    name: rhnsd
    enabled: no
    state: stopped
  ignore_errors: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Uninstall Unnecessary Packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ cm_uninstall_packages }}"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Set SELinux to Enforcing RHEL-07-020210, RHEL-07-020211
  selinux:
    policy: targeted
    state: enforcing
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: CM-7 Remove Rsh Trust Files - /etc/hosts.equiv
  file:
    dest: /etc/hosts.equiv
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: Find User Rsh Trust Files
  shell: "find /home -name '.rhosts' -print"
  register: user_rhosts
  check_mode: no
  changed_when: False

- name: CM-7 Remove Rsh Trust Files - ~/.rhosts
  with_items: "{{ user_rhosts.stdout_lines }}"
  file:
    dest: "{{ item }}"
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-3(d),CM-3(e),CM-6(d),CM-6(3) Install AIDE
  yum:
    name: aide
    state: present
    disablerepo: '*'
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: "CM-3(d),CM-3(e),CM-6(d),CM-6(3) Initialize AIDE - EL7"
  command: "/sbin/aide --init"
  args:
    creates: /var/lib/aide/aide.db.new.gz
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: "CM-3(d),CM-3(e),CM-6(d),CM-6(3) Initialize AIDE - EL6"
  command: "/usr/sbin/aide --init"
  args:
    creates: /var/lib/aide/aide.db.new.gz
  when: ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-3(d),CM-3(e),CM-6(d),CM-6(3) Copy AIDE Database
  command: cp /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
  args:
    creates: /var/lib/aide/aide.db.gz
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-3(d),CM-3(e),CM-6(d),CM-6(3) Schedule AIDE
  cron:
    name: aide
    minute: "{{ aide_minute }}"
    hour: "{{ aide_hour }}"
    day: "{{ aide_day_of_month }}"
    weekday: "{{ aide_day_of_week }}"
    month: "{{ aide_month }}"
    cron_file: aide
    user: root
    job: "/sbin/aide --check"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-3(d),CM-3(e),CM-6(d),CM-6(3) Schedule AIDE
  cron:
    name: aide
    minute: "{{ aide_minute }}"
    hour: "{{ aide_hour }}"
    day: "{{ aide_day_of_month }}"
    weekday: "{{ aide_day_of_week }}"
    month: "{{ aide_month }}"
    cron_file: aide
    user: root
    job: "/usr/sbin/aide --check"
  when: ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: CM-7 Add nodev, nosuid, noguid Options to /dev/sh,
  mount:
    name: /dev/shm
    src: tmpfs
    state: present
    opts: rw,nosuid,nodev,noexec,auto,nouser,async,relatime
    fstype: swap
    dump: 1
    passno: 2
  when: ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name:  CM-6(b),366,RHEL-07-010441 Do Not Allow SSH Environment Options
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PermitUserEnvironment no"
    state: present
  tags:
    - CAT-II

- name: CM-6(d),RHEL-06-000518 Verify and Correct File Permissions with RPM
  shell: for FILE_PATH in $(rpm -Va | grep '^.M'); do rpm --setperms $(rpm -qf "$FILE_PATH"); done

- name: CM-7 Disable Bluetooth Service
  service:
    name: bluetooth
    enabled: no
    state: stopped
  ignore_errors: yes
