- name: Checking if gdm exists
  stat: path=/etc/gdm
  register: gdm

- name: RHEL-07-010430 operating system must not allow an unattended or automatic logon   
  lineinfile:
    dest: /etc/gdm/custom.conf
    regexp: "^AutomaticLoginEnabled"
    insertafter: "^.daemon]"
    line: "AutomaticLoginEnabled=false"
  when: gdm.stat.exists == true
  tags:
    - CAT-I  
  
- name: RHEL-07-010431 operating system must not allow guest logon
  lineinfile:
    dest: /etc/gdm/custom.conf
    regexp: "^TimedLoginEnabled"
    insertafter: "^.daemon]"
    line: "TimedLoginEnabled=false"
  when: gdm.stat.exists == true
  tags:
    - CAT-I    

- name: Removing additional gdm profiles
  lineinfile:
    dest: /etc/dconf/profile/user
    regexp: '(^(user-db:(?!user)))|(^(system-db:(?!local)))'
    state: absent
    mode: 0644
    backup: yes    
  when: gdm.stat.exists == true
  tags:
    - CAT-II

- name: Setting user and local gdm databases
  lineinfile:
    dest: /etc/dconf/profile/user
    line: "{{ item }}"
    state: present
    mode: 0644
    backup: yes
  with_items:
    - user-db:user
    - system-db:local
  when: gdm.stat.exists == true
  tags:
    - CAT-II
    
- name: RHEL-07-010030 Display DoD banner via graphical user logon
  copy:
    src: 01-banner-message
    dest: /etc/dconf/db/local.d/01-banner-message
  when: gdm.stat.exists == true
  tags:
    - CAT-II               
             
- name: RHEL-07-010060,RHEL-07-010070,RHEL-07-010073,RHEL-07-010074
  blockinfile:
    dest: /etc/dconf/db/local.d/00-screensaver
    block: |
      [org/gnome/desktop/screensaver]
      lock-enabled=true
      idle-activation-enabled=true
      idle-delay=uint32 900
      lock-delay=uint32 5
    create: yes
    mode: 0644
    backup: yes
  when: gdm.stat.exists == true
  tags:
    - CAT-II  
  
- name: RHEL-07-010071 Initiate session lock after 15 minutes
  blockinfile:
    dest: /etc/dconf/db/local.d/locks/session
    block: |
      /org/gnome/desktop/screensaver/idle-delay 
      /org/gnome/desktop/screensaver/lock-delay 
      /org/gnome/desktop/session/idle-delay        
    create: yes
    mode: 0644
    backup: yes
  when: gdm.stat.exists == true
  tags:
    - CAT-II   

- name: Setting gdm local permissions
  file:
    path: /etc/dconf/db/local
    mode: 0644
  when: gdm.stat.exists == true
  tags:
  - CAT-II   
       
- name: Updating dconf
  shell: dconf update
  register: result
  when: gdm.stat.exists == true
  tags:
  - CAT-II