- name: IR-5 System Audit Logs Must Have Mode 0640 or Less Permissive
  file:
    path: /var/log/audit/audit.log
    mode: 640
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high

- name: Ensure audit is Installed
  yum:
    name: audit
    state: present
    disablerepo: '*'
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms

- name: Enable auditd service
  service:
    name: auditd
    state: started
    enabled: yes

- name: IR-5,RHEL-07-030351 Configure auditd space_left Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "space_left_action = email"
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: IR-5 Configure auditd admin_space_left Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "admin_space_left_action = email"
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: AU-1(b),AU-4,AU-5(1),AU-5(a),IR-5,RHEL-07-030352 Configure auditd mail_acct Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "action_mail_acct = root"
    state: present
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II

- name: Find commands with setuid/setgid bit set on /
  shell: find / -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null
  check_mode: no
  register: find_result

- name:  IR-5 Add Audit Rules
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/stig.rules
    force: yes
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: IR-5 System Audit Logs Must Have Mode 0640 or Less Permissive (1/4)
  file:
    path: /var/log/audit/audit.log
    mode: 0640
    state: file
    group: root
    owner: root
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
