- name: MA-1(b) Ensure Red Hat GPG Key Installed
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high

- name: MA-1(b) Ensure gpgcheck Enabled In Main Yum Configuration
  replace:
    dest: /etc/yum.conf
    regexp: 'gpgcheck=0'
    replace: 'gpgcheck=1'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high

# - name: Find All Yum Repos - EL 6
#   shell: "/bin/ls /etc/yum.repos.d/*.repo"
#   register: yum_repos
#   changed_when: False
#   when: ansible_distribution_major_version == "6"
#
# - name: Find All Yum Repos - EL 7
#   shell: "/usr/bin/ls /etc/yum.repos.d/*.repo"
#   register: yum_repos
#   changed_when: False
#   when: ansible_distribution_major_version == "7"

- name: Find all yum repos
  find:
    paths: "/etc/yum.repos.d"
    pattern: "*.repo"
  register: yum_repos

# - name: Show YUM repos
#   debug: var=yum_repos

- name: MA-1(b) Ensure gpgcheck Enabled For All Yum Package Repositories
  with_items: "{{ yum_repos }}"
  replace:
    dest: "{{ item.path }}"
    regexp: 'gpgcheck=0'
    replace: 'gpgcheck=1'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high

- name: MA-4 Install openswan or libreswan Package
  yum:
    name: "{{ vpn_package }}"
    state: present
