- name: Enable Randomized Layout of Virtual Address Space
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: 'kernel.randomize_va_space ='
    line: 'kernel.randomize_va_space = 2'
  tags:
    - CCE-26999-3

- name: Enable ExecShield
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: 'kernel.exec-shield ='
    line: 'kernel.exec-shield = 1'
  tags:
    - CCE-27007-4

- name: Disable Network Router Discovery Daemon (rdisc)
  service:
    name: rdisc
    state: stopped
    enabled: no

- name: Ensure rsyslog is Installed
  yum:
    name: rsyslog
    state: present

- name: Enable rsyslog Service
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Disable PRELINKING by Default
  lineinfile:
    dest: /etc/sysconfig/prelink
    create: yes
    regexp: 'PRELINKING=yes'
    line: 'PRELINKING=yes'

- name: Disable existing PRELINKING
  command: /usr/sbin/prelink -ua
  ignore_errors: yes

- name: Disable Ctrl-Alt-Del Reboot Activation
  copy:
    src: control-alt-delete.override
    dest: /etc/init/control-alt-delete.override
  when: ansible_distribution_major_version == "6"

- name: Do Not Allow SSH Environment Options
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ".*PermitUserEnvironment.*"
    line: "PermitUserEnvironment no"

- name: Set Last Login/Access Notification
  lineinfile:
    dest: /etc/pam.d/system-auth
    line: "session\t    required\t  pam_lastlog.so showfailed"
    state: present

- name: Remove sendmail
  yum:
    name: sendmail
    state: absent

- name: Install postfix
  yum:
    name: postfix
    state: present

- name: Start and enable postfix
  service:
    name: postfix
    enabled: yes
    state: started

- name: Checking if gdm exists
  stat: path=/etc/gmd
  register: gdm

- name: RHEL-07-010430 operating system must not allow an unattended or automatic logon   
  lineinfile:
    dest: /etc/gdm/custom.conf
    regexp: "^AutomaticLoginEnabled"
    insertafter: "^.daemon]"
    line: "AutomaticLoginEnabled=false"
  when: gdm.stat.exists == true
  tags:
    - CAT-I  
  
- name: RHEL-07-010431 operating system must not allow guest logon
  lineinfile:
    dest: /etc/gdm/custom.conf
    regexp: "^TimedLoginEnabled"
    insertafter: "^.daemon]"
    line: "TimedLoginEnabled=false"
  when: gdm.stat.exists == true
  tags:
    - CAT-I    

- name: RHEL-07-010030 Display DoD banner via graphical user logon
  copy:
    src: 01-banner-message
    dest: /etc/dconf/db/local.d/01-banner-message
  when: gdm.stat.exists == true
  tags:
    - CAT-I
        
- name: RHEL-07-010060 Enable user session lock
  blockinfile:
    dest: /etc/dconf/db/local.d/00-screensaver     
    block: |
      [org/gnome/desktop/screensaver] 
      lock-enabled=true
    create: yes      
  when: gdm.stat.exists == true
  tags:
    - CAT-II   

- name: RHEL-07-010073 Initiate lock session after 15 minutes of inactivity
  lineinfile:
    dest: /etc/dconf/db/local.d/00-screensaver
    insertafter: "lock-enabled=true"   
    line: "idle-activation-enabled=true"
  when: gdm.stat.exists == true
  tags:
    - CAT-II
  
- name: RHEL-07-010071 Initiate session lock after 15 minutes
  blockinfile:
    dest: /etc/dconf/db/local.d/locks/session
    block: |
      /org/gnome/desktop/screensaver/idle-delay 
      /org/gnome/desktop/screensaver/lock-delay 
      /org/gnome/desktop/session/idle-delay        
    create: yes
  when: gdm.stat.exists == true
  tags:
    - CAT-II   
    
- name: RHEL-07-010070 Initiate screensaver after 15 minutes
  lineinfile:
    dest: /etc/dconf/db/local.d/00-screensaver
    insertafter: "idle-activation-enabled=true"   
    line: "idle-delay=uint32 900"
  when: gdm.stat.exists == true
  tags:
    - CAT-II   
    
- name: RHEL-07-010074 Initiate session lock when screensaver is activated
  lineinfile:
    dest: /etc/dconf/db/local.d/00-screensaver
    insertafter: "lock-delay=uint32 5"   
    line: "lock-delay=uint32 5"
  when: gdm.stat.exists == true
  tags:
    - CAT-II    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    