- name: SI-7 Ensure Red Hat GPG Key Installed
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high

- name: SI-7 Ensure gpgcheck Enabled In Main Yum Configuration
  replace:
    dest: /etc/yum.conf
    regexp: 'gpgcheck=0'
    replace: 'gpgcheck=1'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high

- name: Find All Yum Repos - EL 6
  shell: "/bin/ls /etc/yum.repos.d/*.repo"
  register: yum_repos
  changed_when: False
  when: ansible_distribution_major_version == "6"

- name: SI-7 Ensure gpgcheck Enabled For All Yum Package Repositories - RHEL 6
  with_items: "{{ yum_repos.stdout_lines }}"
  replace:
    dest="{{ item }}"
    regexp='gpgcheck=0'
    replace='gpgcheck=1'
  when: ansible_distribution_major_version == "6"
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high

- name: Find All Yum Repos - EL 7
  shell: "/usr/bin/ls /etc/yum.repos.d/*.repo"
  register: yum_repos
  changed_when: False
  when: ansible_distribution_major_version == "7"

- name: SI-7 Ensure gpgcheck Enabled For All Yum Package Repositories - RHEL 7
  with_items: "{{ yum_repos.stdout_lines }}"
  replace:
    dest="{{ item }}"
    regexp='gpgcheck=0'
    replace='gpgcheck=1'
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high

- name: SI-7 Use Only Approved Ciphers
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ".*Ciphers.*"
    line: "Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc"

- name: SI-7,RHEL-06-000518 Verify and Correct File Permissions with RPM
  shell: for FILE_PATH in $(rpm -Va | grep '^.M'); do rpm --setperms $(rpm -qf "$FILE_PATH"); done

- name: Find Log Files
  shell: grep -e "\$IncludeConfig[[:space:]]\+[^[:space:];]\+" /etc/rsyslog.conf | cut -d ' ' -f 2
  register: log_files

- name: SI-11 Ensure System Log Files Have Correct Permissions
  shell: chmod 600 {{ item }}
  args:
    executable: /bin/bash
  with_items: "{{ log_files.stdout_lines }}"
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high
  - log_files

- name: SI-11 Ensure /etc/rc.d/rc.local has user-executable permission (in order to be actually executed during boot)
  file:
    path: /etc/rc.d/rc.local
    mode: "u+x"

- name: SI-11 Ensure /var/log/boot.log has correct permissions
  file:
    path: /var/log/boot.log
    mode: 0600
  when: ansible_distribution_major_version == "6"
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high
  - log_files

- name: SI-11 Ensure /var/log/boot.log has correct permissions at boot
  lineinfile:
    dest: /etc/rc.local
    line: '/bin/chmod 600 /var/log/boot.log'
  when: ansible_distribution_major_version == "6"
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high
  - log_files
#
# - name: SI-11 Ensure System Log Files Have Correct Permissions - /var/log/boot.log
  # shell: echo "/bin/chmod 600 /var/log/boot.log" >> /etc/rc.local
  # args:
    # executable: /bin/bash
  # when: ansible_distribution_major_version == "6"
  # tags:
  # - conf-low
  # - conf-medium
  # - conf-high
  # - int-low
  # - int-medium
  # - int-high
  # - avail-low
  # - avail-medium
  # - avail-high
