- name: SC-5,SC-7 Disable Kernel Parameter for Sending ICMP Redirects by Default
  sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-5 Disable Kernel Parameter for Sending ICMP Redirects for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high

- name: SC-5 Disable Kernel Parameter for IP Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-5,SC-7 Disable Kernel Parameter for Accepting Source-Routed Packets By Default
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high


- name: SC-5,SC-7 Disable Kernel Parameter for Accepting Secure Redirects By Default
  sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-5,SC-7 Disable Kernel Parameter for Accepting ICMP Redirects By Default
  sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-5 Enable Kernel Parameter to Ignore ICMP Broadcast Echo Requests
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-5 Enable Kernel Parameter to Ignore Bogus ICMP Error Responses
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-5,SC-7 Enable Kernel Parameter to Use Reverse Path Filtering for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-5,SC-7 Enable Kernel Parameter to Use Reverse Path Filtering by Default
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-5 Disable Core Dumps for All Users
  lineinfile:
    dest: /etc/security/limits.conf
    line: '*     hard   core    0'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-2 Disable Interactive Boot
  lineinfile:
    dest: /etc/sysconfig/init
    regexp: ".*PROMPT.*"
    line: "PROMPT=no"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: SC-5(3) Enable Kernel Parameter to Log Martian Packets
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
