- name: SI-7 Ensure Red Hat GPG Key Installed
  rpm_key:
    state=present
    key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high

- name: SI-7 Ensure gpgcheck Enabled In Main Yum Configuration
  replace:
    dest=/etc/yum.conf
    regexp='gpgcheck=0'
    replace='gpgcheck=1'
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high

- name: Find All Yum Repos
  shell: "/usr/bin/ls /etc/yum.repos.d/*.repo"
  register: yum_repos
  changed_when: False
  always_run: True

- name: SI-7 Ensure gpgcheck Enabled For All Yum Package Repositories
  with_items: "{{ yum_repos.stdout_lines }}"
  replace:
    dest="{{ item }}"
    regexp='gpgcheck=0'
    replace='gpgcheck=1'
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high
