- name: Restrict Virtual Console Root Logins
  lineinfile:
    dest: /etc/securetty
    regexp: '^vc'
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-6
    - AC-6(2)

- name: Restrict Serial Port Root Logins
  lineinfile:
    dest: /etc/securetty
    regexp: 'ttyS[0-9]'
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-6
    - AC-6(2)

- name: List Users
  shell: "cat /etc/passwd | cut -d: -f1"
  register: system_users
  changed_when: False
  check_mode: no
  tags:
  - AC
  - AC-6
  - AC-6(8)

- name: List UIDs
  shell: "cat /etc/passwd | cut -d: -f3"
  register: system_uids
  changed_when: False
  check_mode: no
  tags:
    - AC
    - AC-6
    - AC-6(8)

- name: Ensure that System Accounts Do Not Run a Shell Upon Login
  with_together:
    - "{{ system_users.stdout_lines }}"
    - "{{ system_uids.stdout_lines }}"
  user:
    name: "{{ item.0 }}"
    shell: /sbin/nologin
  when: (item.1 < 500) and (item.1 > 0)
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-6
    - AC-6(8)

- name: Verify Only Root Has UID 0
  with_together:
    - "{{ system_users.stdout_lines }}"
    - "{{ system_uids.stdout_lines }}"
  user:
    name: "{{ item.0 }}"
    state: absent
  when: (item.1 == 0) and (item.0 != "root")
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-6
    - IA
    - IA-2
    - IA-2(1)

- name: Prevent Log In to Accounts With Empty Password - /etc/pam.d/system-auth
  replace:
    dest: /etc/pam.d/system-auth
    regexp: nullok
    follow: true
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(c)
    - IA-5(1)

- name: Prevent Log In to Accounts With Empty Password - /etc/pam.d/password-auth
  replace:
    dest: /etc/pam.d/password-auth
    regexp: nullok
    follow: true
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(a)
    - IA-5(1)

- name: Find User's With Passwords That Aren't Shadowed
  shell: 'grep -E -v :x:  /etc/passwd | cut -d: -f1'
  register: bad_users
  check_mode: no
  changed_when: False
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(h)

- name: Find Passwords That Aren't Shadowed
  shell: 'grep -E -v :x:  /etc/passwd | cut -d: -f2'
  register: bad_passwords
  changed_when: False
  check_mode: no
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(h)

- name: Verify All Account Password Hashes are Shadowed - /etc/passwd
  with_together:
    - "{{ bad_users.stdout_lines }}"
    - "{{ bad_passwords.stdout_lines }}"
  replace:
    dest: /etc/passwd
    regexp: '^{{ item.0 }}:{{ item.1 }}:'
    replace: '{{ item.0 }}:x:'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(h)

- name: Verify All Account Password Hashes are Shadowed - /etc/shadow
  with_together:
    - "{{ bad_users.stdout_lines }}"
    - "{{ bad_passwords.stdout_lines }}"
  user:
    name: "{{ item.0 }}"
    password: "{{ item.1 }}"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: All GIDs referenced in /etc/passwd must be defined in /etc/group
  debug:
    msg: "TO-DO"

- name: Verify No netrc Files Exist
  debug:
    msg: "TO-DO"

- name: Set Password Minimum Length - /etc/login.defs
  lineinfile:
    dest: /etc/login.defs
    regexp: "PASS_MIN_LEN *[0-9]*"
    state: present
    line: "PASS_MIN_LEN    14"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - IA-5(a)
    - IA-5(1)

- name: Set Password Minimum Length - /etc/security/pwquality.conf
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: '^minlen ='
    line: "minlen = 15"
  when: ansible_distribution_major_version == "7"
  tags:
    - CAT-II
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - IA-5(a)
    - IA-5(1)

- name: Set Password Minimum Age
  lineinfile:
    dest: /etc/login.defs
    regexp: "PASS_MIN_DAYS *[0-9]"
    state: present
    line: "PASS_MIN_DAYS     1"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - IA-5(1)
    - IA-5(d)

- name: Set Password Maximum Age
  lineinfile:
    dest: /etc/login.defs
    regexp: "PASS_MAX_DAYS *[0-9]*"
    state: present
    line: "PASS_MAX_DAYS     60"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(g)
    - IA-5(1)
    - IA-5(d)

- name: Set Password Warning Age
  lineinfile:
    dest: /etc/login.defs
    regexp: "PASS_WARN_AGE *[0-9]"
    state: present
    line: "PASS_WARN_AGE     7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - AC
    - AC-2
    - AC-2(2)

- name: Set Account Expiration Following Inactivity
  lineinfile:
    dest: /etc/default/useradd
    regexp: '.*INACTIVE.*'
    line: 'INACTIVE=35'
  tags:
  - AC
  - AC-2
  - AC-2(2)
  - AC-2(3)

- name: Ensure All Accounts on the System Have Unique Names
  debug:
    msg: "TO-DO"

- name: Assign Expiration Date to Temporary Accounts
  debug:
    msg: "TO-DO"
  tags:
  - AC
  - AC-2
  - AC-2(2)
  - AC-2(3)

- name: Set Password Retry Prompts Permitted Per-Session
  debug:
    msg: "TO-DO"
  tags:
  - IA
  - IA-5
  - IA-5(c)

- name: Set Password Minimum Digit Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: '^dcredit ='
    line: "dcredit = -1"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-2

- name: Set Password Minimum Uppercase Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: '^ucredit ='
    line: "ucredit = -1"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-2

- name: Set Password Minimum Special Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: 'ocredit ='
    line: "ocredit = -1"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-2

- name: Set Password Minimum Lowercase Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: '^lcredit ='
    line: "lcredit = -1"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-2

- name: Set Password Strength Minimum Different Characters
  lineinfile:
    dest: /etc/security/pwquality.conf
    regexp: '^difok ='
    line: "difok = 4"
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-2

- name: Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/system-auth (1/3)
  lineinfile:
    dest: /etc/pam.d/system-auth
    insertbefore: "^auth.*pam_unix.so.*"
    line: "auth         required      pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900"
  tags:
  - AC
  - AC-7
  - AC-7(a)

- name: Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/system-auth (2/3)
  lineinfile:
    dest: /etc/pam.d/system-auth
    insertafter: "^auth.*pam_unix.so.*"
    line: "auth      [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900"
  tags:
  - AC
  - AC-7
  - AC-7(a)

- name: Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/system-auth (3/3)
  lineinfile:
    dest: /etc/pam.d/system-auth
    insertbefore: "^account.*pam_unix.so.*"
    line: "account     required      pam_faillock.so"
  tags:
  - AC
  - AC-7
  - AC-7(a)

- name: Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/password-auth (1/3)
  lineinfile:
    dest: /etc/pam.d/password-auth
    insertbefore: "^auth.*pam_unix.so.*"
    line: "auth         required    pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900"
  tags:
  - AC
  - AC-7
  - AC-7(a)

- name: Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/password-auth (2/3)
  lineinfile:
    dest: /etc/pam.d/password-auth
    insertafter: "^auth.*pam_unix.so.*"
    line: "auth      [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900"
  tags:
  - AC
  - AC-7
  - AC-7(a)

- name: Set Deny, Lockout Time, and Interval Count For Failed Password Attempts in /etc/pam.d/password-auth (3/3)
  lineinfile:
    dest: /etc/pam.d/password-auth
    insertbefore: "^account.*pam_unix.so.*"
    line: "account       required      pam_faillock.so"
  tags:
  - AC
  - AC-7
  - AC-7(a)

- name: Limit Password Reuse / Set Password Hashing Algorithm
  lineinfile:
    dest: /etc/pam.d/system-auth
    insertafter: "^password requisite pam_pwquality.so"
    regexp: "^password sufficient pam_unix.so*"
    line: "password sufficient pam_unix.so use_authtok sha512 shadow remember=5"
    state: present
    follow: true
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - IA
    - IA-5
    - IA-5(f)
    - IA-5(1)
    - IA-5(e)
    - IA-5(b)
    - IA-5(c)
    - IA-7
    - RHEL-07-010240
    - RHEL-07-010170

# Now set the password quality in the PAM modules
- name: Set Password Strength - /etc/pam.d/system-auth
  lineinfile:
    dest: /etc/pam.d/system-auth
    regexp: '^password    requisite     pam_pwquality.so'
    line: 'password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type= dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 difok=4 maxrepeat=2'
    follow: yes
    backup: yes
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)
    - IA-5(1)(a)

- name: Set Password Strength - /etc/pam.d/password-auth
  lineinfile:
    dest: /etc/pam.d/password-auth
    regexp: '^password    requisite     pam_pwquality.so'
    line: 'password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type= dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 difok=4 maxrepeat=2'
    follow: yes
    backup: yes
  when: ansible_distribution_major_version == "7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)
    - IA-5(1)(a)

- name: Set Password Strength - /etc/pam.d/system-auth
  lineinfile:
    dest: /etc/pam.d/system-auth
    regexp: '^password    requisite     pam_cracklib.so'
    line: 'password    requisite     pam_cracklib.so try_first_pass local_users_only retry=3 authtok_type= dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 difok=4 maxrepeat=2'
    follow: yes
    backup: yes
  when: ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)
    - IA-5(1)(a)

- name: Set Password Strength - /etc/pam.d/password-auth
  lineinfile:
    dest: /etc/pam.d/password-auth
    regexp: '^password    requisite     pam_cracklib.so'
    line: 'password    requisite     pam_cracklib.so try_first_pass local_users_only retry=3 authtok_type= dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 difok=4 maxrepeat=2'
    follow: yes
    backup: yes
  when: ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)
    - IA-5(1)(a)

- name: Set Password Hashing Algorithm login.defs
  lineinfile:
    dest: /etc/login.defs
    regexp: "^ENCRYPT_METHOD*"
    line: "ENCRYPT_METHOD SHA512"
    state: present
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - IA
    - IA-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)
    - IA-7
    - RHEL-07-010180


- name: Set Password Hashing Algorithm in /etc/libuser.conf
  lineinfile:
    dest: /etc/libuser.conf
    insertafter: "^.default]"
    regexp: "^crypt_style"
    line: "crypt_style = sha512"
    state: present
  tags:
    - CAT-II
    - IA
    - IA-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)
    - IA-7
    - RHEL-07-010190

- name: Set Last Login/Access Notification
  lineinfile:
    dest: /etc/pam.d/system-auth
    line: "session\t    required\t  pam_lastlog.so showfailed"
    state: present

- name: Change default umask
  replace:
    dest: /etc/profile
    regexp: 'umask [0-7]*$'
    replace: 'umask 077'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - SA
    - SA-8

- name: Change default bash umask
  replace:
    dest: /etc/bashrc
    regexp: 'umask [0-7]*$'
    replace: 'umask 077'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - SA
    - SA-8

- name: Change cshell umask
  replace:
    dest: /etc/csh.cshrc
    regexp: 'umask [0-7]*$'
    replace: 'umask 077'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - SA
    - SA-8

- name: Ensure the Default Umask is Set Correctly in login.defs
  replace:
    dest: /etc/login.defs
    regexp: '^UMASK [0-7]*$'
    replace: 'UMASK 077'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - CAT-II
    - SA-6
    - SA-6(b)
    - RHEL-07-021060
    - RHEL-07-020230

- name: Ensure the Default Umask is Set Correctly in /etc/profile
  debug:
    msg: "TO-DO"

- name: Limit the Number of Concurrent Login Sessions Allowed Per User
  lineinfile:
    dest: /etc/security/limits.conf
    regexp: '.* hard maxlogins .*'
    line: "* hard maxlogins 10"
  tags:
  - AC
  - AC-10
