- name: Disable Kernel Parameter for Sending ICMP Redirects by Default
  sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high
    - AC
    - AC-4
    - CM
    - CM-7
    - SC
    - SC-5
    - SC-7

- name: Disable Kernel Parameter for Sending ICMP Redirects for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-medium
    - conf-high
    - int-medium
    - int-high
    - CM
    - SC
    - SC-5
    - SC-5(1)

- name: Disable Kernel Parameter for IP Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - RHEL-07-040730
    - SC
    - SC-5

- name: Configure Kernel Parameter for Accepting Source-Routed Packets for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - SC
    - SC-5

- name: Configure Kernel Parameter for Accepting ICMP Redirects for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - SC
    - SC-5

- name: Configure Kernel Parameter for Accepting Secure Redirects for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - SC
    - SC-5
    - AC
    - AC-4

- name: Configure Kernel Parameter to Log Martian Packets
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - SC
    - SC-5
    - SC-5(a)
    - AC
    - AC-3
    - AC-3(10)

- name: Configure Kernel Parameter for Accepting Source-Routed Packets By Default
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - SC
    - SC-5
    - SC-7
    - AC
    - AC-4

- name: Configure Kernel Parameter for Accepting ICMP Redirects By Default
  sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - SC
    - SC-5
    - SC-7
    - AC
    - AC-4

- name: Configure Kernel Parameter to Ignore Bogus ICMP Error Responses
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - SC
    - SC-5

- name: Configure Kernel Parameter for Accepting Secure Redirects By Default
  sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - SC
    - SC-5
    - SC-7
    - AC
    - AC-4

- name: Configure Kernel Parameter to Ignore ICMP Broadcast Echo Requests
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7
    - SC
    - SC-5

- name: Configure Kernel Parameter to Use TCP Syncookies
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - AC
    - CM-4
    - SC
    - SC-5
    - SC-5(2)
    - SC-5(3)

- name: Configure Kernel Parameter to Use Reverse Path Filtering for All Interfaces
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - AC
    - CM-4
    - SC
    - SC-5
    - SC-7

- name: Configure Kernel Parameter to Use Reverse Path Filtering by Default
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - AC
    - CM-4
    - SC
    - SC-5
    - SC-7

- name: Disable Bluetooth Kernel Modules
  copy:
    src: bluetooth.conf
    dest: /etc/modprobe.d/bluetooth.conf
  tags:
    - AC
    - AC-18
    - AC-18(a)
    - AC-18(d)
    - AC-18(3)

- name: Disable Bluetooth Service
  service:
    name: bluetooth
    enabled: no
    state: stopped
  ignore_errors: yes
  tags:
    - AC
    - AC-18
    - AC-18(a)
    - AC-18(d)
    - AC-18(3)

- name: Disable IPv6 Networking Support Automatic Loading
  lineinfile:
    dest: /etc/modprobe.d/disabled.conf
    create: yes
    regexp: '^options ipv6 disable.*'
    line: 'options ipv6 disable=1'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CM
    - CM-7

- name: Configure Accepting IPv6 Redirects
  sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - CM
    - CM-7

- name: Verify iptables Enabled
  service:
    name: iptables
    state: running
    enabled: yes
  when: ansible_distribution_major_version == 6
  tags:
    - AC
    - AC-4
    - CA
    - CA-3

- name: Check if /etc/sysconfig/iptables exists
  stat:
    path: /etc/sysconfig/iptables
  register: st_ip

- name: Set Default Policy for Incoming Packets
  lineinfile:
    dest: /etc/sysconfig/iptables
    line: ":INPUT DROP [0:0]"
    state: present
    regexp: "^:INPUT ACCEPT.*"
  when: st_ip.stat.exists
  tags:
    - CM
    - CM-7
    - RHEL-06-000120

- name: Set Default iptables Policy for Forwarded Packets
  lineinfile:
    dest: /etc/sysconfig/iptables
    line: ":FORWARD DROP [0:0]"
    state: present
    regexp: "^:FORWARD ACCEPT.*"
  when: st_ip.stat.exists
  tags:
  - RHEL-06-000320
  - CM
  - CM-7

- name: Check if /etc/sysconfig/ip6tables exists
  stat:
    path: /etc/sysconfig/ip6tables
  register: st_ip6

- name: RHEL-06-000523 Set Default ip6tables Policy for Incoming Packets
  lineinfile:
    dest: /etc/sysconfig/ip6tables
    line: ":INPUT DROP [0:0]"
    state: present
    regexp: "^:INPUT ACCEPT.*"
  when: st_ip6.stat.exists
  tags:
    - RHEL-06-000523

- name: Disable DCCP Support
  lineinfile:
    dest: /etc/modprobe.d/system.conf
    create: yes
    regexp: 'install dccp'
    line: 'install dccp /bin/false'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CM
    - CM-7

- name: Disable SCTP Support
  lineinfile:
    dest: /etc/modprobe.d/system.conf
    create: yes
    regexp: 'install sctp'
    line: 'install sctp /bin/false'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CM
    - CM-7

- name: Disable RDS Support
  lineinfile:
    dest: /etc/modprobe.d/system.conf
    create: yes
    regexp: 'install rds'
    line: 'install rds /bin/false'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CM
    - CM-7

- name: Disable TIPC Support
  lineinfile:
    dest: /etc/modprobe.d/system.conf
    create: yes
    regexp: 'install tipc'
    line: 'install tipc /bin/false'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CM
    - CM-7

- name: Install openswan or libreswan Package
  yum:
    name: "{{ vpn_package }}"
    state: present
    disablerepo: '*'
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms
  tags:
    - AC
    - AC-17
    - MA
    - MA-4
    - SC
    - SC-8
